#define DN_CO_CO    "Company Commanding Officer"
#define DN_CO_XO    "Company Executive Officer"
#define DN_CO_MIO   "Mission Intelligence Officer"
#define DN_CO_COLO  "Chief of Logistics"
#define DN_CO_FO    "Forward Observer"

#define DN_PL_PL    "Infantry Platoon Leader"
#define DN_PL_PS    "Infantry Platoon Sergeant"
#define DN_PL_UAV   "Infantry Platoon UAV Operator"
#define DN_PL_JTAC  "Infantry Platoon JTAC"
#define DN_PL_MED   "Infantry Platoon Medic"

#define DN_RS_SL    "Squad Leader"
#define DN_RS_TL    "Squad Fireteam Leader"   // Ohne Granatwerfer
#define DN_RS_AR    "Squad Automatic Rifleman"
#define DN_RS_GRN   "Squad Grenadier"
#define DN_RS_M32   "Squad Grenadier (M32)"
#define DN_RS_LITE  "Squad Rifleman (light)"
#define DN_RS_AC    "Squad Rifleman"
#define DN_RS_LAT   "Squad Light Anti-Tank Rifleman"
#define DN_RS_CM    "Squad Combat Medic"
#define DN_RS_DM    "Squad Designated Marksman"
#define DN_RS_ENG   "Squad Combat Engineer"

#define DN_WS_MMG   "Weapon Squad Medium Machine Gunner"
#define DN_WS_MMGA  "Weapon Squad Assistant MMG"
#define DN_WS_HMG   "Weapon Squad Heavy Machine Gunner"
#define DN_WS_HMGA  "Weapon Squad Assistant HMG"
#define DN_WS_GMG   "Weapon Squad Grenade Machine Gunner"
#define DN_WS_GMGA  "Weapon Squad Assistant GMG"
#define DN_WS_AT    "Weapon Squad AT-Specialist"
#define DN_WS_AAT   "Weapon Squad AT-Assistant"
#define DN_WS_ATGM  "Weapon Squad ATGM-Specialist"
#define DN_WS_AATGM "Weapon Squad ATGM-Assistant"
#define DN_WS_AA    "Weapon Squad AA-Specialist"
#define DN_WS_AAA   "Weapon Squad AA-Assistant"
#define DN_WS_MOR   "Weapon Squad Mortar Gunner"
#define DN_WS_MORA  "Weapon Squad Mortar Assistant"
#define DN_WS_MORAC "Weapon Squad Mortar Ammo Carrier"

#define DN_SF_RM    "Special Team Operator"
#define DN_SF_TL    "Special Team Leader"
#define DN_SF_AR    "Special Team Automatic Rifleman"
#define DN_SF_GRN   "Special Team Grenadier"
#define DN_SF_LAT   "Special Team Light Anti-Tank"
#define DN_SF_MED   "Special Team Medic"
#define DN_SF_DM    "Special Team Marksman"
#define DN_SF_EXP   "Special Team Explosive Specialist"

#define DN_DV_RM    "Combat Diver Operator"
#define DN_DV_TL    "Combat Diver Team Leader"
#define DN_DV_EXP   "Combat Diver Explosive Specialist"
#define DN_DV_MED   "Combat Diver Medic"
#define DN_DV_DM    "Combat Diver Marksman"
#define DN_DV_JTAC  "Combat Diver Terminal Attack Controller"

#define DN_SN_SPOT  "Sniper Spotter"
#define DN_SN_AP    "Sniper (Anti-Personel)"
#define DN_SN_AM    "Sniper (Anti-Materiel)"
#define DN_SN_EXP   "Sniper Explosive Specialist"

#define DN_VE_CRW   "Armored Vehicle Crew"
#define DN_VE_CMD   "Armored Vehicle Commander"
#define DN_VE_JET   "Jet Pilot"
#define DN_VE_HCRW  "Helicopter Crew"
#define DN_VE_HPL   "Helicopter Pilot/Copilot/Gunner"

#define DN_SP_LOG   "Logistician"
#define DN_ME_DCT   "Medical Service Doctor"
#define DN_ME_TL    "Medical Service Team Leader"
#define DN_ME_PIL   "Medical Service Helicopter Pilot"
#define DN_ME_DRV   "Medical Service Driver"